version: "3.9"

services:
  backend:
    build: .
    container_name: knowyourpill_backend
    command: uvicorn main:app --host 0.0.0.0 --8000 --reload
    volumes: - .:app
    ports:
      - "8000:8000"
    env_file:
      - .env.local

  frontend:
    build: .
    image: python:3.11-slim
    container_name: knowyourpill_frontend
    command: streamlit run frontend.py  --server.port=8501 --server.address=0.0.0.0
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    env_file:
      - .env.local
